# Generated by Django 5.0.6 on 2026-05-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='created_for_contest',
            field=models.BooleanField(default=False),
        ),
    ]
